plugins {
    id 'java'
}

group = 'com.unifiedAutomation'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Rest Assured
    testImplementation 'io.rest-assured:rest-assured:5.4.0'

    // Playwright Java
    testImplementation 'com.microsoft.playwright:playwright:1.44.0'

    //Selenium Java
    implementation("org.seleniumhq.selenium:selenium-java:4.45.0")

}

test {
    useJUnitPlatform()
}